version: "3.8"
volumes:
  node_modules:
services:
  node:
    container_name: node_api_rest
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=local
    user: 'node'
    ports:
      - target: 3000
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./app
        target: /home/node/app/
      - type: volume
        source: node_modules
        target: /home/node/app/node_modules
